eport_section_order:
  "Benchmarking-trimming-methods-description":
    order: -1000
  software_versions:
    order: -1001
  "Benchmarking-trimming-summary":
    order: -1002

export_plots: false

run_modules:
  - fastqc
  - fastp
  - cutadapt
  - adapterRemoval
  - sickle
  - trimmomatic
  - bbduk
  - prinseqplusplus
  - bowtie2
  - quast
  - spades
  - custom_content

#extra_fn_clean_exts:
#    - '_fastp'
#    - '.pe.settings'
#    - '.se.settings'

top_modules:
  - "fastqc":
      name: "FastQC (pre-Trimming)"
      path_filters:
        - "*_raw_fastqc_*_fastqc.zip"
  - "fastqc":
      name: "FastQC (post-Trimming)"
      path_filters:
        - "*_trimmed_fastqc_*_fastqc.zip"
  - "cutadapt"
  - "fastp"
  - "bbduk"
  - "adapterRemoval"
  - "sickle"
  - "trimmomatic"
  - "prinseqplusplus"
  - "bowtie2"
  - "quast": 
    path_filters:
        - "*.report.tsv"
  - "custom_content":
      name: "Software Versions" 
# TODO: The following modules are missing 
# - quast

extra_fn_clean_exts:
  - ".txt"
  - ".settings"
  - ".bbduk"
  - ".unmapped"
  - "_filtered"
  - "_processed"

sp:
  fastp:
    fn: "*.fastp.json"
  bowtie2:
    fn: "*.bowtie2.log"
  cutadapt:
    fn: "*.cutadapt.log"
  quast:
    fn: "*.report.tsv"

section_comments:
  general_stats: "By default, all read count columns are displayed as millions (M) of reads."
